# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KintVault < Formula
  desc "Secrets management CLI — encrypt .env files directly in your repo"
  homepage "https://github.com/kint-pro/kint-vault-cli"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v0.1.0/kint-vault-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "191ba1367db2fbdf8d82063949129ba575051de7a2844dfb4607ea0061cc896f"

      define_method(:install) do
        bin.install "kint-vault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v0.1.0/kint-vault-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "7c8c5cef2e87255af5d3152244978865939e35ed980f89da0de9e6e0961a889a"

      define_method(:install) do
        bin.install "kint-vault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v0.1.0/kint-vault-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "3c295312b6205366f8c6bf7cccf479a591ee57b5d64d9cd776efca485693e46e"
      define_method(:install) do
        bin.install "kint-vault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v0.1.0/kint-vault-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "ce45336b837c66bc30474f77ed6567485ca1e89df58617f62cf8c05f6f022e82"
      define_method(:install) do
        bin.install "kint-vault"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kint-vault --version", 0)
  end
end
