# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KintVault < Formula
  desc "Secrets management CLI — encrypt .env files directly in your repo"
  homepage "https://github.com/kint-pro/kint-vault-cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v0.1.1/kint-vault-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "1a7d827ce694fd1c23a2ab527a6f49a61895f45c6523eeb7b736521fa9490ab4"

      define_method(:install) do
        bin.install "kint-vault"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v0.1.1/kint-vault-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "6bcacaf42d3709ba6ce63bf65547c98cd0693eb8075dcb4e4d7352236c44dc82"

      define_method(:install) do
        bin.install "kint-vault"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v0.1.1/kint-vault-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "62df33c30a3c51a72306f744df73264b2847f61c52e348456f8d022113fc5f87"
      define_method(:install) do
        bin.install "kint-vault"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v0.1.1/kint-vault-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "12cfc041b18d6086b7ebf09f709aced72d67a1e32d6672c42457f5ee4efee215"
      define_method(:install) do
        bin.install "kint-vault"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/kint-vault --version", 0)
  end
end
