# This file was generated by GoReleaser. DO NOT EDIT.
cask "kint-vault" do
  name "kint-vault"
  desc "Secrets management CLI — encrypt .env files directly in your repo"
  homepage "https://github.com/kint-pro/kint-vault-cli"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kint-vault"

  on_macos do
    on_intel do
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v#{version}/kint-vault-cli_#{version}_darwin_amd64.tar.gz"
      sha256 "3824386f51c5550f8e486e3dfbea99a0692c065ef58e282d4a0f25bce4a363a9"
    end
    on_arm do
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v#{version}/kint-vault-cli_#{version}_darwin_arm64.tar.gz"
      sha256 "97331ad283be31ff36a95a3452b590f9c21451a45f9cd13a0effc1090995d832"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v#{version}/kint-vault-cli_#{version}_linux_amd64.tar.gz"
      sha256 "a123e8d56fb7c6cee8c41ddf90c04140f3881ef2b18c13c510b87daa4b087837"
    end
    on_arm do
      url "https://github.com/kint-pro/kint-vault-cli/releases/download/v#{version}/kint-vault-cli_#{version}_linux_arm64.tar.gz"
      sha256 "1faac5300eb68cb4afe22b55f747b9e0ed1b22900765e59c76e0ceea4d230b08"
    end
  end

  # No zap stanza required
end
